---
name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: "[BUG] <write a small description here>"
labels: ["bug", "goal: fix"]
---

body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional information?
      description: Any additional information or Is there anything we should know about this bug?
    validations:
      required: false
  - type: dropdown
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms_checklist_docs
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Dev-tanay/Rubik-Cube/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/Dev-tanay/Rubik-Cube/issues)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/Dev-tanay/Rubik-Cube/blob/main/CONTRIBUTING.md)"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false