name: "Documentation 📋"
description: "Suggestions on how to improve our docs"
title: "[DOCS] <write your suggestion here>"
labels: ["documenation", "goal: enhancement"]

body:
  - type: textarea
    id: docs_description
    attributes:
      label: "Issue Description"
      description: "Please provide a brief summary of the documentation issue you would like to address."
    validations:
      required: true

  - type: textarea
    id: screenshots_examples_docs
    attributes:
      label: "Screenshots or Examples (if applicable)"
      description: "Include relevant screenshots or examples to help illustrate the problem."

  - type: textarea
    id: proposed_solution_docs
    attributes:
      label: "Proposed Solution (optional)"
      description: "If you have a proposed solution for the documentation issue, please provide it here."
  - type: checkboxes
    id: terms_checklist_docs
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Dev-tanay/Rubik-Cube/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/Dev-tanay/Rubik-Cube/issues)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/Dev-tanay/Rubik-Cube/blob/main/CONTRIBUTING.md)"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
  